### ISSUE TITLE
Jumpscare PNG doesn't render properly

### ISSUE THREAD

**Issue by Synthrifide** [Weebifying/jumpscare-geode#2]
The audio works fine, but the image appears as black and purple squares.

https://github.com/user-attachments/assets/b87dce7b-6fea-4d62-9902-cb682057a0f0

**Comment by Weebifying** [comment]
did you happen to rename a .jpeg file to "jumpscare.png" without properly converting it

**Comment by Synthrifide** [comment]
Oh that worked, thank you
